version: 0.2 
phases: 
  install: 
    commands:
      - echo install step... 
  pre_build:
    commands :
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - echo build Docker image on 'date'
      - docker build -t group2capstone2:latest .
      - docker tag group2capstone2:latest 962804699607.dkr.ecr.us-west-2.amazonaws.com/group2capstone2:latest
  post_build:
    commands:
      - echo build Docker image complete 'date'
      - echo push latest Docker images to ECR...
      - docker push 962804699607.dkr.ecr.us-west-2.amazonaws.com/group2capstone2:latest
      - printf '[{"name":"initgroup2capstone2", "imageUri":"962804699607.dkr.ecr.us-west-2.amazonaws.com/group2capstone2:latest"}]' > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
