version: 0.2 
phases: 
  install: 
    commands:
      - echo install step... 
  pre_build:
    commands :
      - echo "Installing Terraform"
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.2.0/terraform_1.2.0_linux_amd64.zip
      - unzip -o terraform.zip
      - chmod +x terraform
      - mv terraform /usr/local/bin/
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - echo Installing AWS ECS CLI...
      - curl -Lo /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
      - chmod +x /usr/local/bin/ecs-cli
  build:
    commands:
      - echo "Building infrastructure with Terraform"            
      - terraform version
      - terraform init 
      #- terraform destroy -target aws_ecr_repository.group1-capstone2b-final
      - terraform apply --auto-approve 
      - echo build Docker image on 'date'
      - docker build -t group2capstone2:latest .
      - docker tag group2capstone2:latest 962804699607.dkr.ecr.us-west-2.amazonaws.com/group2capstone2:latest
  post_build:
    commands:
      - echo build Docker image complete 'date'
      - echo push latest Docker images to ECR...
      - docker push 962804699607.dkr.ecr.us-west-2.amazonaws.com/group2capstone2:latest
      - printf '[{"name":"react-todo", "imageUri":"962804699607.dkr.ecr.us-west-2.amazonaws.com/group2capstone2:latest"}]' > imagedefinitions.json
      - aws ecs update-service --cluster group2-capstone2-cluster --service grp2-service --force-new-deployment
artifacts:
  files: imagedefinitions.json
